name: Go Build
on: [push]
jobs:

  build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set branch or tag name var
      run: echo "::set-env name=THIS_REF::${GITHUB_REF#refs/heads/}"

    - name: debug THIS_REF
      run: echo "::debug::THIS_REF is set to ${THIS_REF}"

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Test
      run: go test ./pkg/...

    - name: Build
      run: go build -ldflags "-X main.version=${THIS_REF} -X main.versionCommit=${GITHUB_SHA} -s -w" -v ./cmd/smolserv/
