name: goreleaser
on:
  push:
    tags:
      - 'v*'

jobs:
  test_lint:
    name: test & lint
    runs-on: ubuntu-latest
    steps:

      - name: set up go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: checkout code
        uses: actions/checkout@v2

      - name: go test
        run: go test ./pkg/...

      - name: golangci-lint
        uses: actions-contrib/golangci-lint@v1
        env:
          GOROOT: ""

  goreleaser:
    needs: test_lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
