name: tagged version release
on:
  push:
    tags:
      - 'v*'

jobs:
  test_lint:
    name: test & lint
    runs-on: ubuntu-latest
    steps:
      - name: set up go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: checkout code
        uses: actions/checkout@v2

      - name: go test
        run: go test ./pkg/...

      - name: golangci-lint
        uses: actions-contrib/golangci-lint@v1
        env:
          GOROOT: ""

  goreleaser:
    needs: test_lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: unshallow
        run: git fetch --prune --unshallow

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: test_lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@master

    - name: publish image
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'smolserv'
        DOCKERFILE_PATH: 'Dockerfile'
        BUILD_CONTEXT: '.'
        tag: ${GITHUB_REF##*/}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: outputs
      run: |
        echo "The name:tag of the Docker Image is: $VAR1"
        echo "The docker image is hosted at $VAR2"
      env:
        VAR1: ${{ steps.docker.outputs.IMAGE_SHA_NAME }}
        VAR2: ${{ steps.docker.outputs.IMAGE_URL }}

